server:
  port: 7090

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/StiffMedal30/common-config
          searchPaths: '{application}'
          clone-on-start: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
